include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "build/**"
  errors:
    experimental_member_use: ignore
    deprecated_member_use: ignore
    prefer_final_fields: ignore
